### ISSUE TITLE
liberty_logstash_template.json not working for ES 6 and 7

### ISSUE THREAD

**Issue by Marki4711** [WASdev/sample.logstash.collector#11]
Hello,
we tried the configuration with our Elastic-Search Instance and during the startup of logstash I get this error:
```
[2019-05-29T11:55:34,190][INFO ][logstash.outputs.elasticsearch] Installing elasticsearch template to _template/logstash
[2019-05-29T11:55:34,287][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"Got response code '400' contacting Elasticsearch at URL 'http://elasticsearch-client:9200/_template/logstash'", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:80:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:291:in `perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:278:in `block in perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:373:in `with_connection'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:277:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:285:in `block in Pool'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:352:in `template_put'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:86:in `template_install'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/template_manager.rb:28:in `install'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/template_manager.rb:16:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/common.rb:130:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/common.rb:51:in `block in setup_after_successful_connection'"]}
```
When I change the logstash-config and remove the template, it works fine. It looks like the template is not compatible is ES-Cluster 6.x. The sample files also only mention version 4.x and 5.x.

Could you provide template-files that work with newer ES-Cluster (6.x or even better 6.x and 7.x)

BR,
Matthias

**Comment by fmhwong** [comment]
Hi Matthias,

Are you using `logstashCollector-1.0` or `logstashCollector-1.1` in WebSphere Liberty?  These sample files are currently for ELK 5 only.

Have you looked at JSON logging in the latest Liberty driver?  You can switch messages.log to JSON format or direct the log output to stdout.  You can configure Filebeat to monitor messages.log or read from stdout from Liberty.  Filebeat can ship the log records to your ELK stack.

More information about JSON logging can be found at https://www.ibm.com/support/knowledgecenter/SSD28V_9.0.0/com.ibm.websphere.wlp.core.doc/ae/rwlp_logging.html

**Comment by Marki4711** [comment]
Hi Felix,
I use logstashCollector-1.1. 
Liberty is running on zOS and therefore I have no possibility to install filebeat or similar tools. stdout does not help too. I was informed by a colleague, that the forwarding to a logstash-instance works fine, but  I wasn't aware, that it is only working for ELK 5. What is the best solution to fowared logs from a zOS WLP to central logging? (if possible for Splunk and ElasticSearch)
